CREATE DATABASE USECASE2;
USE USECASE2;

CREATE TABLE STUDENT(ID VARCHAR(5) PRIMARY KEY,NAME VARCHAR(20), DEPARTMENT VARCHAR(4), CGPA FLOAT);
INSERT INTO STUDENT VALUES('S001','ARUN','CS',8),('S002','GITA','CS',7.5),('S003','KUMAR','IT',6),('S004','ROHIT','IT',8.5),('S005','YAMUNA','ECE',9),('S006','YOGESH','ECE',9);

CREATE table COMPANY (ID VARCHAR(5) PRIMARY KEY,NAME VARCHAR(20),LOCATION VARCHAR(20),INTERVIEW_DATE DATE);
INSERT INTO COMPANY VALUES ('C001','MICROSOFT','BANGALORE', '2020-08-01'),('C002','AMAZON','CHENNAI', '2020-09-10'), ('C003','FLIPKART','BANGALORE', '2020-09-15'), ('C004','HONEYWELL','HYDERABAD', '2020-10-30'), ('C005','ACCENTURE','CHENNAI', '2020-11-30'), ('C006','WIPRO','NOIDA', '2020-12-31');

CREATE TABLE PLACEMENTS(S_ID VARCHAR(5),C_ID VARCHAR(5),PACKAGE INT);
INSERT INTO PLACEMENTS VALUES('S001','C001',2000000),('S002','C001',2000000),('S003','C002',1200000),('S004','C004',700000),('S004','C006',400000),('S006','C004',700000);


#1 Write a SQL query to find student who go placed with highest package, along with the name of the company.						
SELECT S.NAME AS STUDENT, C.NAME AS COMPANY, P.PACKAGE AS PACKAGE 
FROM STUDENT AS S INNER JOIN PLACEMENTS AS P ON S.ID = P.S_ID 
INNER JOIN COMPANY AS C ON P.C_ID = C.ID 
WHERE P.PACKAGE = (SELECT MAX(PACKAGE) FROM PLACEMENTS);

#3 Write a SQL query to display total number of students each company has hired.						
SELECT C.NAME AS COMPANY, COUNT( P.S_ID ) AS 'NO OF STUDENTS' FROM PLACEMENTS AS P RIGHT JOIN COMPANY AS C ON P.C_ID = C.ID GROUP BY C.ID ;
 
#8 Yamuna decided that she will attend the interview of companies who's location name starts with 'B', write a query that gets the list of company she can attend								
SELECT NAME , LOCATION FROM COMPANY WHERE LOCATION LIKE 'B%';


#4  Write a SQL query which displays list of companies conducted interview in month of september					

SELECT 'SEPTEMBER' AS MONTH, NAME FROM COMPANY WHERE MONTH(INTERVIEW_DATE)=9 ; 
SELECT monthname('2022-08-10');

#5
SELECT C.NAME, C.INTERVIEW_DATE AS 'DATE' FROM COMPANY AS C HAVING INTERVIEW_DATE < curdate() ;
 
#6 
SELECT  S.NAME AS STUDENT, C.NAME AS COMPANY 
FROM ((STUDENT AS S INNER JOIN PLACEMENTS AS P ON S.ID = P.S_ID )
INNER JOIN COMPANY AS C ON P.C_ID = C.ID )
WHERE P.S_ID =  ( SELECT S_ID FROM PLACEMENTS GROUP BY S_ID HAVING COUNT(S_ID)>1);
 

#2 
SELECT S.NAME AS STUDENT,S.DEPARTMENT, IF(P.C_ID IS NULL, 'NO', 'YES') AS PLACED,IF(P.PACKAGE IS NULL, '-', P.PACKAGE) AS PACKAGE,IF(C.NAME IS NULL, '-', C.NAME)AS COMPANY FROM STUDENT AS S LEFT JOIN PLACEMENTS AS P ON S.ID=P.S_ID LEFT JOIN COMPANY AS C ON C.ID= P.C_ID WHERE S.DEPARTMENT = 'ECE';


#7 Accenture would like to shortlist candidates with CGPA > 7 and no need of student who already got placed, write SQL query that statisfies their given criteria								 
SELECT S.NAME , S.DEPARTMENT,S.CGPA FROM PLACEMENTS AS P RIGHT JOIN STUDENT AS S ON S_ID=ID GROUP BY ID HAVING COUNT(C_ID)<1 AND CGPA>7;


GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'sammy'@'localhost' WITH GRANT OPTION;



 select user from mysql.user;  
 
 
 
 
